export const routes = {
  auth: {
    emailCheck: '/auth/check-email/',
    register: '/auth/register/',
    verify: '/auth/verify-otp/',
    setPassword: '/auth/set-password/',
    login: '/auth/login/',
    refresh: 'auth/token/refresh/',
    logout: '/auth/logout/',
    passwordReset: {
      request: '/auth/password-reset/request/',
      verify: '/auth/password-reset/verify/',
      confirm: '/auth/password-reset/confirm/',
    },
    resendEmailOtp: '/auth/resend-email-verification/',
  },
  users: '/auth/users',
  events: {
    list: '/events/',
    detail: (id: string) => `/events/${id}/`,
    getEventBySlug: (slug: string) => `/events/slug/${slug}/`,
    ticketTypes: (id: string) => `/events/${id}/ticket-types/`,
    guests: '/events/guests/',
    guestDetail: (id: string) => `/events/guests/${id}/`,
    ticketTypesRoot: '/events/ticket-types/',
    ticketTypeDetail: (id: string) => `/events/ticket-types/${id}/`,
    tickets: '/events/tickets/',
    ticketDetail: (id: string) => `/events/tickets/${id}/`,
  },
} as const;
